### ISSUE TITLE
Restricts App in landscape

### ISSUE THREAD

**Issue by ghost** [root-two/react-native-drawer#31]
This seemst o have zero support for landscape.  When app is in landscape my app stays the same width. 

![image](https://cloud.githubusercontent.com/assets/8041420/10299408/8f69e1a2-6b9e-11e5-8bf1-78f98ade9cff.png)

**Comment by rt2zz** [comment]
I just published 1.4.1 which uses onLayout to update the drawer when the viewport changes. Let me know if that works.

**Comment by ghost** [comment]
Now the drawer is broken.  It is stuck on the left and doesn't move anywhere

![image](https://cloud.githubusercontent.com/assets/8041420/10430978/1811aa9a-70b7-11e5-9c64-f53f8ca53c0f.png)

**Comment by ghost** [comment]
Rotate Left twice and it breaks even more... lol

![image](https://cloud.githubusercontent.com/assets/8041420/10431054/9c641cb0-70b7-11e5-95fa-a9a00af056ad.png)

**Comment by ghost** [comment]
The panel shows because of the 50 px offset that is set so it doesnt have to cover the entire screen when it opens

**Comment by rt2zz** [comment]
I tried out various scenarios and could not replicate your issue. Can you send more details, or ideally the actual drawer config including layout styles.

While investigating I did find an issue with re-orientation while the drawer was open that I fixed in 1.4.3.

These things are hard to test and debug because they are dependent on the styles, for which there is endless variety. Any more details would help.

**Comment by ghost** [comment]
It appears that 1.4.5 fixed the issue, I see you said something about view size mistakes so that could be what was causing the issues.  The drawer is no longer showing up when it shouldn't.  I will test the other things now.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/8041420/10436797/87480e24-70dd-11e5-9a3c-9de166cbe23a.png)

If you rotate left twice it seems to mess it up.  Are you listening for the events properly?  Keep in mind that it will give you a different number for each orientation.  I actually wrote code to handle the native events at one point.  Could probably have been done way shorter but I wanted it to be easy to read :-P:

```
  updateOrientation(orientation) {
     var o = {};
     switch (orientation) {
       case 1:
         o = {
           current: 'portrait',
           idle: false,
           facing: ''
         };
         break;
       case 2:
         o = {
           current: 'portrait',
           idle: false,
           facing: ''
         };
         break;
       case 3:
         o = {
          current: 'landscape',
           idle: false,
           facing: ''
         };
         break;
       case 4:
         o = {
           current: 'landscape',
           idle: false,
           facing: ''
         };
         break;
   case 5:
    o = {
      current: this.orientation.current,
      idle: true,
      facing: 'up'
    };
    break;
       case 6:
         o = {
           current: this.orientation.current,
           idle: true,
            facing: 'down'
    };
    break;
     }
     this.orientation = o;
     return o;
   }
```

**Comment by rt2zz** [comment]
I am using `onLayout` to detect viewport changes and resize accordingly. onLayout does not trigger for the 'upside down' orientation, this is possibly a bug in react-native. 

Last I checked there is no way to directly listen to orientation changes from react-native (without the help of a native module).

I think it best to wait until there is resolution on: https://github.com/facebook/react-native/issues/2031

**Comment by cdmoyer** [comment]
having a similar issue, but with the additional caveat, that evening returning to the original up position, the layout is still wrong.

```
    render() {                                                                                                              
        return (                                                                                                            
            <Drawer                                                                                                         
                ref="menu"                                                                                                  
                side="right"                                                                                                
                initializeOpen={false}                                                                                      
                openDrawerOffset={0.3}                                                                                      
                panOpenMask={0}                                                                                             
                acceptPan={false}                                                                                           
                acceptTap={true}                                                                                            
                captureGestures={true}                                                                                      
                type="overlay"                                                                                              
                styles={{drawer: {shadowColor: "#000000", shadowOpacity: 0.4, shadowRadius: 3}, main: {opacity: 1.0}}}   
                tweenHandler={(ratio) => {                                                                                  
                    return {                                                                                                
                        drawer: { shadowRadius: Math.min(ratio*5*5, 5) },                                                   
                        main: { opacity:(2-ratio)/2 },                                                                      
                    }                                                                                                       
                }}                                                                                                          
                content={<Menu />}                                                                                          
                >                                                                                                           
            <Navigator                                                                                                      
                initialRoute={{type: 'main', title: 'Member Deals'}}                                                        
                renderScene={this.renderScene}                                                                              
                />                                                                                                          
            </Drawer>                                                                                                       

        );                                                                                                                  
    }, 
```

Those styles are all inline, the Menu:

```
    render() {                                                                                                           
        return (                                                                                                         
            <View style={styles.menu}>                                                                                   
                <MenuItem text="Settings" />                                                                             
                <MenuItem text="Account" />                                                                              
                <MenuItem text="Rewards" />                                                                              
                <MenuItem text="Terms & Conditions" />                                                                   
            </View>                                                                                                      
            );                                                                                                           
    }  
```

styles:

```
  menu: {                                                                                                                   
      padding: 10,                                                                                                          
      paddingTop: 100,                                                                                                      
      backgroundColor: DARK_GREY,                                                                                           
      flex: 1                                                                                                               
  },                                                                                                                        
  menu_item: {                                                                                                              
      paddingTop: 5,                                                                                                        
      paddingBottom: 5,                                                                                                     
      borderBottomWidth: 1,                                                                                                 
      borderBottomColor: '#fff',                                                                                            
  },                                                                                                                        
  menu_item_text: {                                                                                                         
      color: '#fff',                                                                                                        
      fontSize: 18,                                                                                                         
      paddingLeft: 20                                                                                                       
  }, 
```

First loaded, looks and works great, this is open:
![simulator](https://cloud.githubusercontent.com/assets/48776/10542523/b7a69f52-73e6-11e5-889f-656364a65ac5.png)

rotated left, closed:
![simulator-1](https://cloud.githubusercontent.com/assets/48776/10542542/cd1b7894-73e6-11e5-85b0-afd26362d703.png)

rotated back to "normal" orientation:
![simulator-2](https://cloud.githubusercontent.com/assets/48776/10542549/e190e9a8-73e6-11e5-82b8-8e5b0a42c10f.png)

the other weird thing is that after these orientation changes, the captureGestures and whatnot no longer work, and I can tap the underlying content.

**Comment by rt2zz** [comment]
@cdmoyer what version of react-native-drawer? To be certain can you update to 1.5.1 and tell me if you still experience the problem. I am unable to replicate the problem.

**Comment by cdmoyer** [comment]
@rt2zz Ok, I just made a sample project, trying to narrow it down.  I installed the latest 1.5.2 and can recreate it, here's the barebones I've  got:

```
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  Navigator,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} = React;
var Drawer = require('react-native-drawer');
var Dimensions = require('Dimensions')

var Menu = React.createClass({
    render() {
        return (
            <View style={styles.menu}>
                <Text>Menu Item</Text>
            </View>
            );
    }
});


var Test = React.createClass({
    openMenu() {
        this.refs.menu.open();
    },
    renderScene(route, navigator) {
        if (route.type == 'main') {
            return (
                <View style={{backgroundColor: '#0f0', flex: 1}}>
                <View style={styles.bar}>
                    <Text style={styles.bar_title}>Main</Text>
                    <TouchableOpacity
                        onPress={() => this.openMenu()}>
                        <Text style={styles.bar_menu}>=</Text>
                    </TouchableOpacity>
                </View>
                <TouchableOpacity
                    onPress={() => alert('clicked')} >
                    <View style={{height: 300, width: 100, backgroundColor: '#000', position: 'absolute',top:100, left: 0}} />
                </TouchableOpacity>
               </View>
            );
        }
        else if (route.type == 'details') {
            return <View style={{backgroundColor: '#ff0', flex: 1}} />
        }
    },
  render: function() {
      return (
            <Drawer
                ref="menu"
                side="right"
                initializeOpen={false}
                openDrawerOffset={0.3}
                panOpenMask={0}
                acceptPan={false}
                acceptTap={true}
                captureGestures={true}
                type="overlay"
                styles={{drawer: {shadowColor: "#000000", shadowOpacity: 0.4, shadowRadius: 3}, main: {opacity: 1.0}}}
                tweenHandler={(ratio) => {
                    return {
                        drawer: { shadowRadius: Math.min(ratio*5*5, 5) },
                        main: { opacity:(2-ratio)/2 },
                    }
                }}
                content={<Menu />}
                >
            <Navigator
                initialRoute={{type: 'main', title: 'Main'}}
                renderScene={this.renderScene}
                />
        </Drawer>
    );
  }
});

var styles = StyleSheet.create({
  menu: {
      padding: 10,
      paddingTop: 100,
      backgroundColor: '#666',
      flex: 1
  },
  bar: {
    height: 64,
    paddingTop: 20,
    backgroundColor: '#cfc',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },

  bar_title: {
      color: '#fff',
      fontSize: 22,
      position: 'absolute',
      top: 30,
      left: Dimensions.get('window').width/2,
      width: 250,
      textAlign: 'center',
      marginLeft: -125,
      fontWeight: 'bold',
  },

  bar_menu: {
      color: '#fff',
      fontSize: 28,
      position: 'absolute',
      left: Dimensions.get('window').width - 30,
      top: 5,
  },
});
AppRegistry.registerComponent('Test', () => Test);
```

![simulator](https://cloud.githubusercontent.com/assets/48776/10564675/4e607fd6-758a-11e5-8f09-d7a24f1ad7ad.png)

This is rotated left, not open:
![simulator-1](https://cloud.githubusercontent.com/assets/48776/10564682/5c66f6aa-758a-11e5-8c96-77b64c548041.png)

```
{
  "name": "Test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "~0.13.0-rc",
    "react-native-drawer": "~1.5.2"
  }
}
```

**Comment by rt2zz** [comment]
thank you for the test app, it turns out we were updating the panel widths _after_ the render, hence the issue. I just published 1.5.4 with the fix.

There may be additional issues (it is hard to test every combination of styles/props) so your help trying it out would be greatly appreciated.

**Comment by cdmoyer** [comment]
Awesome, that's working in the test app for me, and also my real app!  Thanks!

I've got one more weird thing where sometimes, only in landscape, you can click through to the content under the drawer... sometimes.  I'll see if I can narrow it down to a test case, as I can't reproduce it in my test app yet.

**Comment by rt2zz** [comment]
@cdmoyer could it be related to when the content is a ScrollView? the pan negotiation for ScrollViews is a little different than normal Touchable elements and there could definitely be edge cases. Also make sure `captureGestures={true}`

**Comment by cdmoyer** [comment]
Ah!  It's definitely a listview under the drawer in my app where I'm seeing that behaviour.  You can click through on the list items, and then once you've moved to the details view, tapping that area closes the drawer.  (Probably because you're no longer on a listview)

**Comment by rt2zz** [comment]
@cdmoyer I am going to close this as I believe all reorientation issues are resolved. 

Feel free to open a seperate issue and we can dig into what is going on with that ListView
